---
- hosts: all
  become: true
  tasks:
  - name: Set-up git
    package:
      name: git
      state: latest
  - name: Install Java
    package:
      name: java
      state: latest
    when: ansible_distribution == 'CentOS'
  - name: Update apt repo
    apt:
      update_cache: yes
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - name: Install Java on Debian/Ubuntu
    package:
      name: openjdk-8-jdk
      state: latest
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - name: Enable Jenkins repository on CentOS
    get_url: 
      url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
    when: ansible_distribution == 'CentOS'
  - name: Enable Jenkins repository on Debian/Ubuntu
    shell: 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - name: Add repo to system on CentOS
    rpm_key:
      key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
      state: present
    when: ansible_distribution == 'CentOS'
  - name: Add repo to system on Debian/Ubuntu
    apt_key:
      url: https://jenkins-ci.org/redhat/jenkins-ci.org.key
      state: present
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - name: Update apt repo 2
    apt:
      update_cache: yes
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - name: Install Jenkins
    package:
      name: jenkins
      state: present
  - name: Ensure Jenkins is running
    service:
      name: jenkins
      state: started
  handlers:
    - name: Restart Jenkins
      service:
        name: jenkins
        state: restarted
...
